import JSZip from "jszip";
import { saveAs } from "file-saver";

export async function downloadWebsiteZip(
  html: string,
  css: string,
  js: string,
  siteName: string = "my-website"
) {
  try {
    // Create a new zip file
    const zip = new JSZip();

    // Add files to the zip
    zip.file("index.html", html);
    zip.file("index.css", css);
    zip.file("index.js", js);

    // Create a placeholder favicon
    zip.file("favicon.ico", "", { base64: true });

    // Create a readme file with instructions
    const readmeContent = `# ${siteName} Website

This website was generated using the Eribot Website Generator.

## Files
- index.html: The main HTML structure of your website
- index.css: All styling for your website
- index.js: JavaScript for handling stream countdown and other functionality

## Hosting and domains
I reccomend hosting on Github pages, tutorial here:
https://pages.github.com/

you can even use a custom domain (aka url) by following this tutorial:
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

to get a custom domain I reccomend namecheap:
https://ap.www.namecheap.com

## Customization
To further customize your website, you can edit the HTML, CSS, and JS files directly.

## Additional info
There's nothing stopping you from removing the footer, but it will make me sad :_( 

## Generated by Eribot
https://eri.bot/
`;

    zip.file("README.md", readmeContent);

    // Generate the zip file
    const zipContent = await zip.generateAsync({ type: "blob" });

    // Clean up the site name for the filename
    const cleanSiteName = siteName
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");

    // Trigger download
    saveAs(zipContent, `${cleanSiteName || "my-website"}.zip`);

    return true;
  } catch (error) {
    console.error("Error creating zip file:", error);
    return false;
  }
}
